[project]
name = "grade-gnn-experiment"
version = "0.1.0"
description = "Refactored experimental suite for the GRADE-GNN paper"
requires-python = ">=3.9"

[project.dependencies]
torch = "*"
torch_geometric = "*"
matplotlib = "*"
numpy = "*"
networkx = "*"
GraphRicciCurvature = "*"
ogb = "*"
pyyaml = "*"

[build-system]
requires = ["setuptools", "wheel"]
backend-path = ["."]
